### ISSUE TITLE
Date in index field

### ISSUE THREAD

**Issue by pinhasyak** [internetitem/logback-elasticsearch-appender#4]
Hi, 
Thank you for release,
New Issue :
Elasticsearch prefer add to index date for better indexing, like logstash do : for example: "_index" : "logstash-2013.11.21"

Please do it for default, some thing like this:
Settings class:
public String getIndex() {
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy.MM.dd");
		return index+"-"+simpleDateFormat.format(new Date());
	}

**Comment by abatkin** [comment]
Good point that the index name should be customizable. I guess that's not something that I came across before since we publish to an alias. Perhaps the index name should allow the same format specification as individual properties (allowing the Logback conversion words) and be evaluated every time. What do you think?

**Comment by pinhasyak** [comment]
I think that you have to take logstash pattern:
http://logstash.net/docs/1.4.0/outputs/elasticsearch#index

**Comment by pinhasyak** [comment]
Hi, can you please release this feature as soon as possible, my elasticsearch admin want indexed per day

**Comment by abatkin** [comment]
I have pushed v1.2. It now uses the same PatternLayout (from the individual fields) for the index's value (which is now evaluated for every log messages).
